name: Build
description: Create a new Docker image
inputs:
  dockerfile_path:
    description: "Path to the Dockerfile"
    required: false
    default: "Dockerfile"
  image_name:
    description: "Name of the Docker image"
    required: true
  tag_name:
    description: "Tag for the Docker image"
    required: false
runs:
  using: composite
  steps:
    - name: Set Docker Image Tag
      run: |
        if [ -z "${{ inputs.tag_name }}" ]; then
          echo "TAG=$(date +%s)" >> $GITHUB_ENV
        else
          echo "TAG=${{ inputs.tag_name }}" >> $GITHUB_ENV
        fi
      shell: bash
    - name: Set Docker Image Name
      run: |
        echo "DOCKER_IMAGE_NAME=${{ inputs.image_name }}:$TAG" >> $GITHUB_ENV
      shell: bash
    - name: Build Docker Image
      run: docker build . --file ${{ inputs.dockerfile_path }} --tag $DOCKER_IMAGE_NAME
      shell: bash