name: Build
description: Build application with Maven and create a new Docker image
inputs:
  dockerfile_path:
    description: "Path to the Dockerfile"
    required: false
    default: "Dockerfile"
runs:
  using: composite
  steps:
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      shell: bash
    - name: Build Docker Image
      run: docker build . --file ${{ inputs.dockerfile_path }} --tag academy:$(date +%s)
      shell: bash