name: Build
description: Create a new Docker image
inputs:
  docker_username:
    description: "docker username"
    required: true
  docker_token:
    description: "docker token"
    required: true
  image_name:
    description: "image name generated"
    required: true 
runs:
  using: composite
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_token }}
    - name: Push Docker Image with tag from input
      run: docker push ${{ inputs.image_name }}
      shell: bash
